# Generated by Django 6.0.7 on 2026-07-24 17:13

import django.db.models.deletion
import django_cryptography.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_patrimonio', models.CharField(help_text='Número de série ou etiqueta de patrimônio', max_length=50, unique=True)),
                ('nome', models.CharField(help_text='Nome identificador do ativo (ex: NB-FIN-01)', max_length=150)),
                ('tipo', models.CharField(choices=[('NOTEBOOK', 'Notebook'), ('DESKTOP', 'Desktop'), ('SERVIDOR', 'Servidor / Cloud'), ('IMPRESSORA', 'Impressora'), ('REDE', 'Equipamento de Rede (Switch/Roteador)'), ('OUTRO', 'Outro')], default='NOTEBOOK', max_length=30)),
                ('status', models.CharField(choices=[('ATIVO', 'Em Uso / Ativo'), ('MANUTENCAO', 'Em Manutenção'), ('ESTOQUE', 'Disponível em Estoque'), ('BAIXADO', 'Descartado / Baixado')], default='ATIVO', max_length=20)),
                ('localizacao', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Setor ou endereço físico', max_length=200, null=True))),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ativos_atribuidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
