# Generated by Django 6.0.7 on 2026-07-24 17:13

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recovery_token',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=64, null=True)),
        ),
        migrations.AlterField(
            model_name='user',
            name='two_factor_secret',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=32, null=True)),
        ),
    ]
