# Generated by Django 6.0.7 on 2026-07-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='slaconfig',
            name='tempo_resolucao_horas',
        ),
        migrations.RemoveField(
            model_name='slaconfig',
            name='tempo_resposta_horas',
        ),
        migrations.AddField(
            model_name='slaconfig',
            name='tempo_resolucao_minutos',
            field=models.IntegerField(default=0, help_text='Tempo limite para a solução final em MINUTOS (Ex: 240 para 4 horas)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slaconfig',
            name='tempo_resposta_minutos',
            field=models.IntegerField(default=0, help_text='Tempo limite para a primeira resposta em MINUTOS (Ex: 30 para meia hora, 120 para 2 horas)'),
            preserve_default=False,
        ),
    ]
